application: hover-mom
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /ping/tasks/.*
  script: hovermom.wsgi.application
  login: admin
  
- url: /.*
  script: hovermom.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'hovermom.settings'
  
builtins:
- remote_api: on
